[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/admin-login"
  to = "/.netlify/functions/admin-login"
  status = 200

[[redirects]]
  from = "/api/admin-session"
  to = "/.netlify/functions/admin-session"
  status = 200

[[redirects]]
  from = "/api/admin-logout"
  to = "/.netlify/functions/admin-logout"
  status = 200
